[Appearance]
icon_theme=breeze-dark
custom_palette=true
cosmic_qt_version=2
standard_dialogs=xdgdesktopportal
color_scheme_path=/home/f/.config/qt5ct/colors/CosmicDark.conf

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\xff\xff\xff\xfd\xff\xff\xff\xe2\0\0\x3\xb8\0\0\x2\xad\0\0\0\0\0\0\0\0\0\0\x3\xb5\0\0\x2\xaa\0\0\0\0\0\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\x3\xb5\0\0\x2\xaa)
