[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\xff\xff\xff\xfd\xff\xff\xff\xe2\0\0\x3\xb8\0\0\x2y\0\0\0\0\0\0\0\0\0\0\x3\xb5\0\0\x2v\0\0\0\0\0\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\x3\xb5\0\0\x2v)

[Appearance]
color_scheme_path=/home/f/.config/qt6ct/colors/CosmicDark.conf
custom_palette=true
standard_dialogs=xdgdesktopportal
icon_theme=breeze-dark
cosmic_qt_version=2
